# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build GTK-4

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y libv4l-dev libgtk-4-dev gobject-introspection

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build CMD
      run: env CGO_ENABLED=0 go build -v
    
    - name: Build GTK-4
      run: go build -v -tags withgtk4 -o marmalade-gtk4

#    - name: Test
#      run: go test -v ./...

    - name: Create Distributable Folder
      run: mkdir dist && mv -t dist python scripts config.json LICENSE marmalade marmalade-gtk4

    - name: Export Distributable Folder
      uses: actions/upload-artifact@v4
      with:
        name: marmalade-gtk4
        path: dist
        if-no-files-found: error
        retention-days: 1
        compression-level: 1
        overwrite: true
