# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build GTK-4

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y libgtk-4-dev libv4l-0t64

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v -tags withgtk4

#    - name: Test
#      run: go test -v ./...

    - name: Create Distributable Folder
      run: mkdir dist && mv -t dist python scripts config.json LICENSE marmalade-gtk4

    - name: Export Distributable Folder
      uses: actions/upload-artifact@v4
      with:
        name: marmaladge-gtk4.zip
        path: dist
        if-no-files-found: error
        retention-days: 1
        compression-level: 1
        overwrite: true
